### ISSUE TITLE
PGP functionality not compatible with current version of GPG 

### ISSUE THREAD

**Issue by tommybonderenka** [rocketjob/iostreams#13]
The current version of GPG has been upgraded to `2.3.1` (https://formulae.brew.sh/formula/gnupg) which is not supported by the gem. 

Is the IOStreams gem going to be updated to support this new default version of GPG?

**Comment by reidmorrison** [comment]
I ran into the same issue this morning after running a brew upgrade. Looks like GnuPG v2.3 is backward compatible with v2.2, so I just raised the allowed version. All tests passed.
Will include this change in a new gem version as soon as I get another JRuby zip codepage issue resolved.
Otherwise, for now you can point at the master branch in github.

**Comment by reidmorrison** [comment]
Pushed rubygem v1.6.1
